### ISSUE TITLE
microVU1 precompile code problem

### ISSUE THREAD

**Issue by Vitt0xLar** [kozarovv/PS2-Configs#5]
Problem with microVU1 precompiler code .

This code doesn't work , i would like to use it because i've found a lots of memory addresses in Scarface but using this code it will freeze at pic1 .
Can you help me ? i've putted something wrong in conig.lua file ?

apiRequest(0.2)

local gpr    		= require("ee-gpr-alias")
local emuObj 		= getEmuObject()
local eeObj			= getEEObject()
local gsObj			= getGsObject()
local eeOverlay 	= eeObj.getOverlayObject()

local eeObj = getEEObject()
local PrecompileAddrs = Queue.new ( { 0x72EFA0, 0x51A388, 0x6FE950, 0x6FB6E0, 0x5099F4, 0x41AE58, 0x727FEC, 0x72286C, 0x72EF90, 0x72EFA4, 0x509668, 0x61F8E8, 0x68E29C, 0x6200C0, 0x75F4B0, 0x72775C, 0x727744 } )

**Comment by kozarovv** [comment]
This code require at least apiRequest(1.2), and emu version that support it. Also code seems to be read per line, so you need to separate addresses also by lines. Here is example code. 

https://drive.google.com/file/d/1L2YxondID65KIAybKVCBH9KgFegqqOeQ/view

**Comment by Vitt0xLar** [comment]
Ok , thanks for answering to me , but witch emu does support apiRequest(1.2) ?
i've tried jak emu and it doesn't stuck at pic1 image , so it supports it , but with jak emu scarface won't start, after Ps2 boot logo i get a black screen , i've tried PAL and NTSC versions.
what can i do ?
